### ISSUE TITLE
[Bug]: Incompatible with sodium

### ISSUE THREAD

**Issue by VaporeonScripts** [someaddons/betterfpsdistances#52]
### Describe the bug you're experiencing

cant use both this mod and sodium mod together

### Reproducability

just put sodium and latest 1.21.1 version of this fabric mod and it wont work

### Mod up to date

- [X] Before submitting this issue I updated to the newest version and reproduced it

### Minecraft version

1.21(1.21.1)

### Modloader version

Fabric

### Logs

no logs

**Comment by someaddons** [comment]
fixed in 4.5

**Comment by tajemniktv** [comment]
Sodium added a break conflict specific to 4.5 version, might be worth upping it to 4.6
(And I think it should be upped as it's a second 4.5, unless I'm wrong, but anyways...)

```json
  "breaks": {
    //(...)
    "betterfpsdist": "\u003c\u003d1.21-4.5", 
```

Changing it to anything else obviously "fixes" the issue

**Comment by VaporeonScripts** [comment]
the issue is not fixed, 
![image](https://github.com/user-attachments/assets/8950968a-faf0-4957-b8e1-74d6424ffee9)

**Comment by Koekieezz** [comment]
any fix yet?
